### ISSUE TITLE
Server Crashed with Exception

### ISSUE THREAD

**Issue by TWhidden** [TWhidden/HolidayShow#17]
Application: HolidayShowServer.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.TypeInitializationException
Stack:
   at System.Data.Entity.QueryableExtensions.FirstOrDefaultAsync[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Linq.IQueryable`1<System.__Canon>, System.Threading.CancellationToken)
   at System.Data.Entity.QueryableExtensions.FirstOrDefaultAsync[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Linq.IQueryable`1<System.__Canon)
   at HolidayShowServer.RemoteClient+<ProcessPacket>d__21.MoveNext()
   at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[[HolidayShowServer.RemoteClient+<ProcessPacket>d__21, HolidayShowServer, Version=1.15.1020.0, Culture=neutral, PublicKeyToken=null]](ProcessPacket>d__21 ByRef)
   at HolidayShowServer.RemoteClient.ProcessPacket(Byte[], HolidayShowLib.ParserProtocolContainer)
   at HolidayShowLib.ByteParserBase.SearchBuffer()
   at HolidayShowLib.ByteParserBase.BytesReceived(Byte[])
   at HolidayShowServer.RemoteClient.EndBeginRead(System.IAsyncResult)
   at System.Net.LazyAsyncResult.Complete(IntPtr)
   at System.Net.ContextAwareResult.CompleteCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Net.ContextAwareResult.Complete(IntPtr)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(System.Object, IntPtr)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32, UInt32, System.Threading.NativeOverlapped_)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32, UInt32, System.Threading.NativeOverlapped_)

**Comment by TWhidden** [comment]
Closed - Moved to EF7, also containerized for Docker.
